// Generated by scripts/render-voices.py from scripts/voice-script.json.
export type VoiceCharacterId = 'a-tang' | 'shen-yan' | 'lu-yin';
export type VoiceEvent = 'intro' | 'capture' | 'lost' | 'strongCapture' | 'strongLost' | 'thinking' | 'win' | 'lose' | 'undo';
export type VoiceLine = {
  readonly characterId: VoiceCharacterId;
  readonly event: VoiceEvent;
  readonly text: string;
  readonly src: string;
};

export const voiceLines: Record<VoiceCharacterId, Record<VoiceEvent, readonly VoiceLine[]>> = {
  "a-tang": {
    "intro": [
      {
        "characterId": "a-tang",
        "event": "intro",
        "text": "来啦！今天我可是偷偷练过的。",
        "src": "./voices/a-tang/intro-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "intro",
        "text": "棋子摆好啦，陪我痛快下一局！",
        "src": "./voices/a-tang/intro-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "intro",
        "text": "先说好，赢了可不许笑我。",
        "src": "./voices/a-tang/intro-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "intro",
        "text": "嘿，茶还热着呢，咱们开局吧！",
        "src": "./voices/a-tang/intro-4.mp3"
      }
    ],
    "capture": [
      {
        "characterId": "a-tang",
        "event": "capture",
        "text": "嘿嘿，这颗棋子归我啦！",
        "src": "./voices/a-tang/capture-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "capture",
        "text": "机会来了！我可就不客气咯。",
        "src": "./voices/a-tang/capture-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "capture",
        "text": "吃到啦！这步还不错吧？",
        "src": "./voices/a-tang/capture-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "capture",
        "text": "哎呀，你怎么把它送过来啦！",
        "src": "./voices/a-tang/capture-4.mp3"
      }
    ],
    "lost": [
      {
        "characterId": "a-tang",
        "event": "lost",
        "text": "哎呀！我怎么没看见这步！",
        "src": "./voices/a-tang/lost-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lost",
        "text": "呜，我的棋子！走得太急了。",
        "src": "./voices/a-tang/lost-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lost",
        "text": "可惜可惜，这下得认真啦。",
        "src": "./voices/a-tang/lost-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lost",
        "text": "被你抓到了！下回我可记住了。",
        "src": "./voices/a-tang/lost-4.mp3"
      }
    ],
    "strongCapture": [
      {
        "characterId": "a-tang",
        "event": "strongCapture",
        "text": "哇！这回可逮到大家伙了！",
        "src": "./voices/a-tang/strongCapture-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongCapture",
        "text": "漂亮！这一步，我能开心好久！",
        "src": "./voices/a-tang/strongCapture-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongCapture",
        "text": "嘿嘿，辛苦你把大礼送上门！",
        "src": "./voices/a-tang/strongCapture-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongCapture",
        "text": "拿下！我就说，这招有用吧！",
        "src": "./voices/a-tang/strongCapture-4.mp3"
      }
    ],
    "strongLost": [
      {
        "characterId": "a-tang",
        "event": "strongLost",
        "text": "啊？这么重要的棋子也丢啦！",
        "src": "./voices/a-tang/strongLost-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongLost",
        "text": "完了完了，我刚才在想什么呀！",
        "src": "./voices/a-tang/strongLost-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongLost",
        "text": "哎呀，好心疼！这步亏大了。",
        "src": "./voices/a-tang/strongLost-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "strongLost",
        "text": "不行不行，打起精神，还能下！",
        "src": "./voices/a-tang/strongLost-4.mp3"
      }
    ],
    "thinking": [
      {
        "characterId": "a-tang",
        "event": "thinking",
        "text": "等一下嘛，我在想个好主意。",
        "src": "./voices/a-tang/thinking-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "thinking",
        "text": "这里，还是那里呢？让我想想。",
        "src": "./voices/a-tang/thinking-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "thinking",
        "text": "别催别催，好棋马上就来。",
        "src": "./voices/a-tang/thinking-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "thinking",
        "text": "这盘棋，比我想的还好玩呢。",
        "src": "./voices/a-tang/thinking-4.mp3"
      }
    ],
    "win": [
      {
        "characterId": "a-tang",
        "event": "win",
        "text": "赢啦！今天练的招数真管用！",
        "src": "./voices/a-tang/win-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "win",
        "text": "哈哈，这一局归我！还来吗？",
        "src": "./voices/a-tang/win-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "win",
        "text": "我赢了！快让我得意一小会儿。",
        "src": "./voices/a-tang/win-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "win",
        "text": "太好啦！多亏你陪我练棋。",
        "src": "./voices/a-tang/win-4.mp3"
      }
    ],
    "lose": [
      {
        "characterId": "a-tang",
        "event": "lose",
        "text": "啊，还是你厉害！再陪我练一局嘛。",
        "src": "./voices/a-tang/lose-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lose",
        "text": "输啦。不过，我好像学到新招了！",
        "src": "./voices/a-tang/lose-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lose",
        "text": "好吧，这回认输，下回可不一定哦。",
        "src": "./voices/a-tang/lose-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "lose",
        "text": "你的棋真好！这盘我得好好想想。",
        "src": "./voices/a-tang/lose-4.mp3"
      }
    ],
    "undo": [
      {
        "characterId": "a-tang",
        "event": "undo",
        "text": "好啦好啦，这一步重新想！",
        "src": "./voices/a-tang/undo-1.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "undo",
        "text": "给你一次机会，也让我缓口气。",
        "src": "./voices/a-tang/undo-2.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "undo",
        "text": "倒回去啦，这回可要看仔细哦。",
        "src": "./voices/a-tang/undo-3.mp3"
      },
      {
        "characterId": "a-tang",
        "event": "undo",
        "text": "没关系，咱们慢慢下。",
        "src": "./voices/a-tang/undo-4.mp3"
      }
    ]
  },
  "shen-yan": {
    "intro": [
      {
        "characterId": "shen-yan",
        "event": "intro",
        "text": "清茶已备，请落子。",
        "src": "./voices/shen-yan/intro-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "intro",
        "text": "难得闲暇，你我手谈一局。",
        "src": "./voices/shen-yan/intro-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "intro",
        "text": "今日风静，正适合与君对弈。",
        "src": "./voices/shen-yan/intro-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "intro",
        "text": "棋逢知己，是件雅事。请。",
        "src": "./voices/shen-yan/intro-4.mp3"
      }
    ],
    "capture": [
      {
        "characterId": "shen-yan",
        "event": "capture",
        "text": "这枚棋子，我便收下了。",
        "src": "./voices/shen-yan/capture-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "capture",
        "text": "恰有空隙，可以一试。",
        "src": "./voices/shen-yan/capture-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "capture",
        "text": "承让，这一步略占先机。",
        "src": "./voices/shen-yan/capture-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "capture",
        "text": "局面有趣起来了。",
        "src": "./voices/shen-yan/capture-4.mp3"
      }
    ],
    "lost": [
      {
        "characterId": "shen-yan",
        "event": "lost",
        "text": "唉，是我疏忽了一处。",
        "src": "./voices/shen-yan/lost-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lost",
        "text": "好眼力，果然瞒不过你。",
        "src": "./voices/shen-yan/lost-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lost",
        "text": "这一子，丢得有些可惜。",
        "src": "./voices/shen-yan/lost-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lost",
        "text": "走得急了，容我稳一稳。",
        "src": "./voices/shen-yan/lost-4.mp3"
      }
    ],
    "strongCapture": [
      {
        "characterId": "shen-yan",
        "event": "strongCapture",
        "text": "妙。这一步，恰好落在关键处。",
        "src": "./voices/shen-yan/strongCapture-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongCapture",
        "text": "如此厚礼，沈某就笑纳了。",
        "src": "./voices/shen-yan/strongCapture-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongCapture",
        "text": "棋路渐明，心中也畅快了。",
        "src": "./voices/shen-yan/strongCapture-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongCapture",
        "text": "时机已至，这一子值得。",
        "src": "./voices/shen-yan/strongCapture-4.mp3"
      }
    ],
    "strongLost": [
      {
        "characterId": "shen-yan",
        "event": "strongLost",
        "text": "唉，顾此失彼，损失不小。",
        "src": "./voices/shen-yan/strongLost-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongLost",
        "text": "落子之前，终究少算了一步。",
        "src": "./voices/shen-yan/strongLost-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongLost",
        "text": "你这手棋，着实出人意料。",
        "src": "./voices/shen-yan/strongLost-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "strongLost",
        "text": "失了要子，更需沉住气。",
        "src": "./voices/shen-yan/strongLost-4.mp3"
      }
    ],
    "thinking": [
      {
        "characterId": "shen-yan",
        "event": "thinking",
        "text": "容我斟酌片刻。",
        "src": "./voices/shen-yan/thinking-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "thinking",
        "text": "此处有几条棋路，须仔细分辨。",
        "src": "./voices/shen-yan/thinking-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "thinking",
        "text": "不妨喝口茶，慢慢思量。",
        "src": "./voices/shen-yan/thinking-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "thinking",
        "text": "棋盘方寸，变化却不少。",
        "src": "./voices/shen-yan/thinking-4.mp3"
      }
    ],
    "win": [
      {
        "characterId": "shen-yan",
        "event": "win",
        "text": "承让了。这一局下得尽兴。",
        "src": "./voices/shen-yan/win-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "win",
        "text": "侥幸胜出，多谢赐教。",
        "src": "./voices/shen-yan/win-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "win",
        "text": "胜负已分，茶香还在。再来一局？",
        "src": "./voices/shen-yan/win-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "win",
        "text": "与你对弈，果然是件乐事。",
        "src": "./voices/shen-yan/win-4.mp3"
      }
    ],
    "lose": [
      {
        "characterId": "shen-yan",
        "event": "lose",
        "text": "甘拜下风，今日受教了。",
        "src": "./voices/shen-yan/lose-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lose",
        "text": "好棋。这一局，值得细细回味。",
        "src": "./voices/shen-yan/lose-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lose",
        "text": "是我棋差一着，佩服。",
        "src": "./voices/shen-yan/lose-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "lose",
        "text": "输赢之外，还有所得。多谢。",
        "src": "./voices/shen-yan/lose-4.mp3"
      }
    ],
    "undo": [
      {
        "characterId": "shen-yan",
        "event": "undo",
        "text": "无妨，重新斟酌便是。",
        "src": "./voices/shen-yan/undo-1.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "undo",
        "text": "落子可回，思路也可再理一理。",
        "src": "./voices/shen-yan/undo-2.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "undo",
        "text": "你我切磋，不必拘谨。请。",
        "src": "./voices/shen-yan/undo-3.mp3"
      },
      {
        "characterId": "shen-yan",
        "event": "undo",
        "text": "且回到此处，再看一遍。",
        "src": "./voices/shen-yan/undo-4.mp3"
      }
    ]
  },
  "lu-yin": {
    "intro": [
      {
        "characterId": "lu-yin",
        "event": "intro",
        "text": "坐吧。山中无事，正好下棋。",
        "src": "./voices/lu-yin/intro-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "intro",
        "text": "棋如远山，须一步一步看。请。",
        "src": "./voices/lu-yin/intro-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "intro",
        "text": "老夫许久未逢对手，来吧。",
        "src": "./voices/lu-yin/intro-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "intro",
        "text": "心静些，棋盘会告诉你答案。",
        "src": "./voices/lu-yin/intro-4.mp3"
      }
    ],
    "capture": [
      {
        "characterId": "lu-yin",
        "event": "capture",
        "text": "嗯，这一子，收了。",
        "src": "./voices/lu-yin/capture-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "capture",
        "text": "顺势而行，便是此处。",
        "src": "./voices/lu-yin/capture-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "capture",
        "text": "机会既来，不妨取之。",
        "src": "./voices/lu-yin/capture-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "capture",
        "text": "有舍有得，棋路才开。",
        "src": "./voices/lu-yin/capture-4.mp3"
      }
    ],
    "lost": [
      {
        "characterId": "lu-yin",
        "event": "lost",
        "text": "嗯，是老夫看漏了。",
        "src": "./voices/lu-yin/lost-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lost",
        "text": "好。你这一手有分量。",
        "src": "./voices/lu-yin/lost-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lost",
        "text": "一子虽失，心不可乱。",
        "src": "./voices/lu-yin/lost-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lost",
        "text": "唉，仍有疏漏啊。",
        "src": "./voices/lu-yin/lost-4.mp3"
      }
    ],
    "strongCapture": [
      {
        "characterId": "lu-yin",
        "event": "strongCapture",
        "text": "好！这一子，落得痛快。",
        "src": "./voices/lu-yin/strongCapture-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongCapture",
        "text": "等的便是这个时机。",
        "src": "./voices/lu-yin/strongCapture-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongCapture",
        "text": "局势至此，已有几分眉目。",
        "src": "./voices/lu-yin/strongCapture-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongCapture",
        "text": "老夫这番耐心，倒没白费。",
        "src": "./voices/lu-yin/strongCapture-4.mp3"
      }
    ],
    "strongLost": [
      {
        "characterId": "lu-yin",
        "event": "strongLost",
        "text": "唉，这一步，代价不轻。",
        "src": "./voices/lu-yin/strongLost-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongLost",
        "text": "后生可畏。老夫小看你了。",
        "src": "./voices/lu-yin/strongLost-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongLost",
        "text": "大意了。残局更需定力。",
        "src": "./voices/lu-yin/strongLost-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "strongLost",
        "text": "失之毫厘，差得便远了。",
        "src": "./voices/lu-yin/strongLost-4.mp3"
      }
    ],
    "thinking": [
      {
        "characterId": "lu-yin",
        "event": "thinking",
        "text": "莫急，再看远些。",
        "src": "./voices/lu-yin/thinking-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "thinking",
        "text": "静一静，路便清楚了。",
        "src": "./voices/lu-yin/thinking-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "thinking",
        "text": "这几子之间，尚有余味。",
        "src": "./voices/lu-yin/thinking-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "thinking",
        "text": "一时进退，不妨多想一步。",
        "src": "./voices/lu-yin/thinking-4.mp3"
      }
    ],
    "win": [
      {
        "characterId": "lu-yin",
        "event": "win",
        "text": "承让。老夫这把骨头，还下得动。",
        "src": "./voices/lu-yin/win-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "win",
        "text": "棋局已定。你下得不错。",
        "src": "./voices/lu-yin/win-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "win",
        "text": "胜在耐心。愿你下次再来。",
        "src": "./voices/lu-yin/win-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "win",
        "text": "好一盘棋，山中今日不寂寞。",
        "src": "./voices/lu-yin/win-4.mp3"
      }
    ],
    "lose": [
      {
        "characterId": "lu-yin",
        "event": "lose",
        "text": "好，好。后浪已到，老夫服了。",
        "src": "./voices/lu-yin/lose-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lose",
        "text": "这局是你赢了。落子很有章法。",
        "src": "./voices/lu-yin/lose-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lose",
        "text": "老夫输得明白，也输得痛快。",
        "src": "./voices/lu-yin/lose-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "lose",
        "text": "棋道无尽，今日又长一分见识。",
        "src": "./voices/lu-yin/lose-4.mp3"
      }
    ],
    "undo": [
      {
        "characterId": "lu-yin",
        "event": "undo",
        "text": "无妨，再看清楚些。",
        "src": "./voices/lu-yin/undo-1.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "undo",
        "text": "退一步，或许另有天地。",
        "src": "./voices/lu-yin/undo-2.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "undo",
        "text": "来，重新落子。莫急。",
        "src": "./voices/lu-yin/undo-3.mp3"
      },
      {
        "characterId": "lu-yin",
        "event": "undo",
        "text": "肯回头细看，也是进境。",
        "src": "./voices/lu-yin/undo-4.mp3"
      }
    ]
  }
};
