"""Regenerate the authored NPC reaction bank with Edge neural TTS.

Install build-time dependency: python -m pip install edge-tts==7.2.8
Run: python scripts/render-voices.py
Existing nonempty clips are kept; use --force to regenerate them.
The game itself does not depend on Python, edge-tts, or network access.
"""

import argparse
import asyncio
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "voice-script.json"
EVENTS = (
    "intro", "capture", "lost", "strongCapture", "strongLost",
    "thinking", "win", "lose", "undo",
)
# Rate/pitch are modest prosody changes, not a claim of acted emotional speech.
PROSODY = {
    "intro": (0, 0), "capture": (5, 3), "lost": (-5, -3),
    "strongCapture": (8, 5), "strongLost": (-7, -4),
    "thinking": (-5, -1), "win": (6, 4), "lose": (-6, -3), "undo": (0, 0),
}


def catalogue(data):
    result = {}
    for character_id, character in data.items():
        if set(character["lines"]) != set(EVENTS):
            raise ValueError(f"Incomplete events: {character_id}")
        result[character_id] = {}
        for event in EVENTS:
            texts = character["lines"][event]
            if len(texts) < 4 or len(set(texts)) != len(texts):
                raise ValueError(f"Need four distinct variants: {character_id}/{event}")
            result[character_id][event] = [
                {
                    "characterId": character_id,
                    "event": event,
                    "text": text,
                    "src": f"./voices/{character_id}/{event}-{index}.mp3",
                }
                for index, text in enumerate(texts, 1)
            ]
    return result


def write_manifest(bank):
    target = ROOT / "src" / "audio" / "voiceLines.ts"
    target.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "// Generated by scripts/render-voices.py from scripts/voice-script.json.\n"
        f"export type VoiceCharacterId = {' | '.join(repr(character_id) for character_id in bank)};\n"
        "export type VoiceEvent = " + " | ".join(repr(event) for event in EVENTS) + ";\n"
        "export type VoiceLine = {\n"
        "  readonly characterId: VoiceCharacterId;\n"
        "  readonly event: VoiceEvent;\n"
        "  readonly text: string;\n"
        "  readonly src: string;\n"
        "};\n\n"
        "export const voiceLines: Record<VoiceCharacterId, Record<VoiceEvent, readonly VoiceLine[]>> = "
    )
    target.write_text(header + json.dumps(bank, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")


async def render(args, data, bank):
    import edge_tts

    limiter = asyncio.Semaphore(args.concurrency)
    total = sum(len(lines) for events in bank.values() for lines in events.values())
    completed = 0

    async def one(character_id, event, line):
        nonlocal completed
        output = ROOT / "public" / line["src"][2:]
        if output.exists() and output.stat().st_size > 1500 and not args.force:
            completed += 1
            return
        async with limiter:
            character = data[character_id]
            rate_delta, pitch_delta = PROSODY[event]
            rate = f"{character['rate'] + rate_delta:+d}%"
            pitch = f"{character['pitch'] + pitch_delta:+d}Hz"
            output.parent.mkdir(parents=True, exist_ok=True)
            partial = output.with_suffix(".part")
            for attempt in range(4):
                try:
                    speech = edge_tts.Communicate(
                        line["text"], character["voice"], rate=rate, pitch=pitch,
                        connect_timeout=15, receive_timeout=30,
                    )
                    await speech.save(str(partial))
                    if partial.stat().st_size < 1500:
                        raise RuntimeError("TTS produced no useful audio")
                    partial.replace(output)
                    completed += 1
                    print(f"[{completed}/{total}] {character_id}/{output.name} ({output.stat().st_size} bytes)", flush=True)
                    break
                except Exception:
                    partial.unlink(missing_ok=True)
                    if attempt == 3:
                        raise
                    await asyncio.sleep(2 ** attempt)

    jobs = [
        (character_id, event, line)
        for character_id, events in bank.items()
        for event, lines in events.items()
        for line in lines
    ]
    if args.samples:
        jobs = [(cid, event, bank[cid][event][0]) for cid in bank for event in ("capture", "lost")]
    await asyncio.gather(*(one(*job) for job in jobs))

    if not args.samples:
        assets = []
        for _, _, line in jobs:
            path = ROOT / "public" / line["src"][2:]
            content = path.read_bytes()
            assets.append({"src": line["src"], "bytes": len(content), "sha256": hashlib.sha256(content).hexdigest()})
        report = ROOT / "public" / "voices" / "assets.json"
        report.write_text(json.dumps({"generator": "edge-tts 7.2.8", "clips": assets}, indent=2) + "\n", encoding="utf-8")
        print(f"Completed: {len(assets)} clips, {sum(asset['bytes'] for asset in assets):,} bytes", flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--manifest-only", action="store_true")
    parser.add_argument("--samples", action="store_true", help="Render one capture/loss pair per character first")
    parser.add_argument("--concurrency", type=int, default=3, choices=range(1, 5))
    args = parser.parse_args()
    data = json.loads(SCRIPT.read_text(encoding="utf-8"))
    bank = catalogue(data)
    write_manifest(bank)
    if not args.manifest_only:
        asyncio.run(render(args, data, bank))


if __name__ == "__main__":
    main()
